### ISSUE TITLE
cannot find this cookbook on supermarket.chef.io

### ISSUE THREAD

**Issue by epinault** [chef-boneyard/chef_slack#1]
### Cookbook version

Any
### Chef-client version

0.12.10
### Platform Details

Ubuntu 14.04 
### Scenario:

Trying use this cookbook but nowhere to be found
### Steps to Reproduce:

 knife cookbook site download chef_slack
### Expected Result:

download the cookbook
### Actual Result:

ERROR: The object you are looking for could not be found
Response:

**Comment by eeyun** [comment]
Yep this cookbook totally doesn't exist on the supermarket currently. We should have more follow-up on this in the immediate future.

**Comment by tas50** [comment]
I'll get this pushed up
