### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by epinault** [chef-boneyard/chef_slack#2]
### Cookbook version

latest
### Chef-client version

0.12.10
### Platform Details

Ubuntu 14.04
### Scenario:

Trying to include it
### Steps to Reproduce:

in the doc , it says to add depend 'slack' instead 'chef_slack'
also should be include_recipe 'chef_slack'

**Comment by eeyun** [comment]
You are correct. This is fixed in another readme based PR here https://github.com/chef-cookbooks/chef_slack/pull/3
