### ISSUE TITLE
Document not proper

### ISSUE THREAD

**Issue by varunpalekar** [chef-boneyard/chef_slack#4]
Document not follow resource `Custom Resource Usage` and also `notifies`. 

Please use following: 

`chef_slack_notify "Say Summat!"`

```
chef_slack_notify "send_notification_message" do
  message "This is a notification message"
  webhook_url 'https://hooks.slack.com/services/XXXX/XXXXXXX/XXXXXX'
  not_if { node['im_boring'] }
end
```

```
chef_slack_notify "channel_nothing" do
  message "heres a message to kick off later"
  username 'test_user'
  channels ['foo','bar']
  webhook_url 'https://hooks.slack.com/services/XXXX/XXXXXXX/XXXXXX'
  action :nothing
end

something "talk_as_test_user_to_multiple_channels" do
  notifies :notify, "chef_slack_notify[channel_nothing]", :immediately
end
```

**Comment by cheeseplus** [comment]
I'm not clear what this issue is regarding, the resource is called `slack_notify` as per https://github.com/chef-cookbooks/chef_slack/blob/master/resources/notify.rb#L1. The resource name doesn't have to match the cookbook name although it is common. Closing.

**Comment by varunpalekar** [comment]
@cheeseplus Please call your cookbook names `chef_slack` from any cookbook and came to know that you it gives error (not able to call). I have faced the problem which I have reported to you. 

And another problem of calling `notifies :say, "slack[channel_nothing]", :immediately`, it giving me error. This is due to you have no action named `say` in `https://github.com/chef-cookbooks/chef_slack/blob/master/resources/notify.rb#L1` but have `notify` action. 
so just want you to update docs accordingly. 

Thanks.
